language: erlang # no C/shell language support; use least-loaded worker(s)

before_install:
    - sudo apt-get install -y libfuse-dev cdbs

install:
    - dpkg-buildpackage -us -uc
    - sudo dpkg -i ../romdirfs_*.deb

script: romdirfs --version # no tests yet
