language: c

compiler:
  - gcc
  - clang

before_install: sudo apt-get install -y libfuse-dev

install:
    - make CC=$CC
    - sudo make install prefix=/usr/local

script: romdirfs --version # no tests yet
