language: erlang # no C/shell language support; use least-loaded worker(s)

before_install: sudo apt-get install -y libfuse-dev

install:
    - make
    - sudo make install prefix=/usr/local

script: romdirfs --version # no tests yet
