name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [--all-features, --no-default-features]
    steps:
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install libfuse
        run: sudo apt-get install libfuse-dev

      - name: Get sources
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace ${{ matrix.features }}

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace ${{ matrix.features }}
